### ISSUE TITLE
Crash on blacklist

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/Metro#6] opened 2020-06-30 08:15 UTC
App crashes when adding folder to blacklist

Android Q

**Comment by fusionneur** [comment] 2020-06-30 08:15
Version 3.5.8 0628

**Comment by fusionneur** [comment] 2020-06-30 08:20
FATAL EXCEPTION: main
Process: io.github.muntashirakon.Music, PID: 15910
java.lang.IllegalStateException: Fragment BlacklistPreferenceDialog{6e7e2cb} (3db08522-5773-4b98-b2ab-66edf95f0c7d)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Unknown Source:31)
	at io.github.muntashirakon.music.preferences.BlacklistPreferenceDialog.onFolderSelection(Unknown Source:10)
	at io.github.muntashirakon.music.dialogs.BlacklistFolderChooserDialog.I73HSbgPyADguGKqZhsROfaf8w(Unknown Source:7)
	at io.github.muntashirakon.music.dialogs.ms94jpv3sGgC7I5zOT6CTpFwlSnJU.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(Unknown Source:47)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27582)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7695)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by marissarousseau** [comment] 2020-06-30 16:15
Just wanted to add that there may be an issue with storage access for the app in general on Android 10. If I try to delete an album or song, it says I need to grant scoped storage access, but then it never prompts me to do so.

**Comment by MuntashirAkon** [comment] 2020-06-30 17:35
> Just wanted to add that there may be an issue with storage access for the app in general on Android 10. If I try to delete an album or song, it says I need to grant scoped storage access, but then it never prompts me to do so.

The devs are well aware of these issues and will probably take care of them soon. If not, I'll try and fix them instead.

**Comment by MuntashirAkon** [comment] 2020-06-30 17:36
Duplicate of #2. I've already fixed this and you'll probably get an update tomorrow.

**Closed by MuntashirAkon** 2020-06-30 17:36 UTC
