### ISSUE TITLE
Retro player intrusive messages

### ISSUE THREAD

**Issue by scottbetza** [MuntashirAkon/Metro#163] opened 2023-04-05 09:29 UTC
Latest version. Get pop ups from retro somehow. See screenshots.

![Screenshot_20230405-052654](https://user-images.githubusercontent.com/14841113/230040540-12dcc633-254c-4699-87e4-fa3b70de3551.png)
![Screenshot_20230405-052656](https://user-images.githubusercontent.com/14841113/230040556-9335e36a-4b8b-4840-a968-6cc4d33d019a.png)
![Screenshot_20230405-052700](https://user-images.githubusercontent.com/14841113/230040560-bce154fa-d79d-4531-bb2d-c98f41ce623f.png)

**Comment by eniris** [comment] 2023-04-05 15:14
same unpleasant behavior for me 😬

**Comment by kipuyanoo** [comment] 2023-04-05 16:28
There's a file somewhere, `PlagiarismUtil.kt` that shows these. Nuking the file from the source tree should fix it.

**Comment by weaponmasterjax** [comment] 2023-04-05 16:34
yea very bothering
will make a pr for this

**Comment by 0xMANFRE** [comment] 2023-04-05 16:39
Duplicate of #160.
This is already fixed, just wait for the F-droid build on the official F-droid repo. It does take a few days, not dev's fault, it's the F-droid build procedure that is slow.

**Comment by scottbetza** [comment] 2023-04-06 10:15
> Duplicate of #160. This is already fixed, just wait for the F-droid build on the official F-droid repo. It does take a few days, not dev's fault, it's the F-droid build procedure that is slow.

Situations like this are why devs should always put their apk builds on github too. Many prefer to use tools like obtanium which can pull the builds from git.

**Comment by kipuyanoo** [comment] 2023-04-06 22:34
I'm going to build it myself lmao

**Comment by kipuyanoo** [comment] 2023-04-06 22:35
Not mad or calling out the dev bc it is absolutely F-Droid having a resources shortage but I am an impatient leezo6

**Comment by DavidRLTG** [comment] 2023-04-07 15:24
Could someone build it, upload the apk somewhere, and post a link here, please?

**Comment by weaponmasterjax** [comment] 2023-04-07 16:12
> Could someone build it, upload the apk somewhere, and post a link here, please?

https://github.com/weaponmasterjax/Metro/releases/tag/v.6.6.6666
mine using my keys and signed.
For TEMPORARY USE ONLY.
You must uninstall before installing fdroid version.

**Comment by DavidRLTG** [comment] 2023-04-07 16:14
Thank you man, I really appreciate it :)

**Closed** 2023-04-11 10:49 UTC

**Comment by kipuyanoo** [comment] 2023-04-11 14:39
Awesome. Thanks.
