### ISSUE TITLE
Can't give give sdcard permission / can't delete song on sdcard

### ISSUE THREAD

**Issue by eNV25** [MuntashirAkon/Metro#13] opened 2020-08-23 19:32 UTC
**Describe the bug**
Cannot give sdcard write permission. Cannot delete songs.

**How To Reproduce**
1. Press 3 dot menu of individual song > delete song
2. Confirm delete
3. Swipe through informational "slide"

**Expected behavior**
System's file selection screen doesn't appear. This is not a problem in Retro.

**Device info:**
 - Device: Huawei Y9 2019
---
<table>
<tr><td>App version</td><td>3.5.10</td></tr>
<tr><td>App version code</td><td>10443</td></tr>
<tr><td>Android build version</td><td>9.1.0.296C675</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>JKM-AL00a 9.1.0.296(C675E4R1P7)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWJKM-HM</td></tr>
<tr><td>Device model</td><td>JKM-AL00a</td></tr>
<tr><td>Device product name</td><td>JKM-AL00aIN</td></tr>
<tr><td>Device hardware name</td><td>kirin710</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
<tr><td>Language</td><td>auto</td></tr>
</table>

**Additional context**
I have all my songs in sdcard. This app needs sdcard access to delete files. Not a problem in Retro.

Unrelated: Do you plan to stay in sync with Retro?

**Comment by MuntashirAkon** [comment] 2020-08-23 19:54
Sorry, I am unable to reproduce this issue in 3.5.10. Could you share any graphics content regarding this issue.

> Unrelated: Do you plan to stay in sync with Retro?

Yes, I intend to. Retro is currently going through some major internal changes, which I believe I shouldn't skip.

**Comment by eNV25** [comment] 2020-08-24 19:49
![record](https://user-images.githubusercontent.com/61089994/91089246-f044fc80-e670-11ea-8eac-7aeb12f4230e.gif)

**Comment by tleydxdy** [comment] 2020-09-08 06:45
Same issue here. moto x4 lineageos, 3.5.10 installed from f-droid

**Comment by MuntashirAkon** [comment] 2020-09-26 08:37
This should be fixed in v3.5.11

**Comment by eNV25** [comment] 2020-09-29 04:35
Now the information thing doesn't even show. It just says 0 song deleted.

**Comment by Nesaijn** [comment] 2020-10-31 19:32
I have installed it from the F-Droid Store and it says that I have version 4.0.010 Pro.
I experience the same issue. The same goes for editing the tag which does not change when the music is on the sdcard.

Xperia XA2
LineageOS 17.1

**Comment by khlinuxdeveloper** [comment] 2021-02-09 18:54
_Store: F-Droid 
Version: 4.0.010 Pro
Model of device: Samsung Galaxy Note 10+ with Android 11 (One UI 3.0)_

**Problem**: When I edit the tag of the songs that are on the SDcard, nothing changes. And also in the folders tab, there is no option for browsing between files in external memory (SDcard). Like @Nesaijn, it does not notify of any access to the SD card as it happens with other applications.

**Closed** 2021-02-11 10:13 UTC
Labels: bug
